SELECT  [Month]
      , [Year_]
      , [name_]
      , [ids]
      , [avg_players]
      , [gains]
      , [percent_gains]
      , [peak_players]
      , [Last_Updated]
FROM [dbo].[steam_optimised_all_games_all_data]
ORDER BY name_ DESC